# Generated by Django 6.0.1 on 2026-03-17 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedIndicator',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('economic', 'Economic'), ('health', 'Health'), ('education', 'Education'), ('leadership', 'Leadership')], max_length=20)),
                ('source', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField()),
                ('trend_data', models.JSONField(default=list)),
                ('disaggregation_location', models.JSONField(default=list)),
                ('disaggregation_age', models.JSONField(default=list)),
                ('regional_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Detailed Indicators',
            },
        ),
        migrations.CreateModel(
            name='GapAlert',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('economic', 'Economic'), ('health', 'Health'), ('education', 'Education'), ('leadership', 'Leadership'), ('crossCutting', 'Cross-Cutting')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=50)),
                ('trend', models.CharField(max_length=50)),
                ('trend_direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('neutral', 'Neutral')], max_length=20)),
                ('time_range', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=list)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='api.metric')),
            ],
        ),
    ]
